### ISSUE TITLE
Notification handler 'workspace/didChangeConfiguration' failed with message

### ISSUE THREAD

**Issue by X-DCB** [microsoft/vscode-emmet-helper#64] opened 2021-06-20 04:16 UTC
I always check for updates but I already got the latest update and still, the error shows up.
emmetExtensionsPath.trim is not a function

**Comment by rzhao271** [comment] 2021-07-15 21:20
@X-DCB if you open your settings file in the JSON editor (`workbench.action.openSettingsJson` command), what do you get for `emmetExtensionsPath`?

Here's generally how mine looks:
```json
"emmet.extensionsPath": [
    "C:\\Users\\<username>\\<rest-of-path>"
]
```

**Comment by X-DCB** [comment] 2021-08-17 05:41
sorry for the delay 😅
i installed VS code insider and sometimes the error pops up
![image](https://user-images.githubusercontent.com/28706220/129669722-da045a48-507d-4e25-9969-8027fb93b90c.png)

**Comment by rzhao271** [comment] 2021-08-17 15:17
Hm, looks like it's an empty array. Can you check in the settings JSON file to confirm that's the case?
Also, when does the error message show up for you?

**Comment by X-DCB** [comment] 2021-09-07 03:37
> Hm, looks like it's an empty array. Can you check in the settings JSON file to confirm that's the case?
> Also, when does the error message show up for you?

what should be the array values, I mean what are the target locations?

**Comment by rzhao271** [comment] 2021-09-07 15:47
If you're not using snippets, an empty array is fine. I'm curious whether the value is being saved differently in the settings json file, though? Can you run the `workbench.action.openSettingsJson` command and see if there's an entry for `emmet.extensionsPath`? If that entry exists, can you paste me the value?

**Comment by rzhao271** [comment] 2021-10-08 16:57
I'll close this issue for now as part of the housekeeping iteration. If you have some answers for https://github.com/microsoft/vscode-emmet-helper/issues/64#issuecomment-914421549 I can re-open the issue.

**Comment by CherryDT** [comment] 2023-01-11 23:47
@rzhao271 I'm having the same problem, this issue still exists. For me, `emmet.extensionsPath` is simply not existing at all (undefined) if it never got anything set. But even if I manually add it as empty array to the remote settings JSON file, nothing changes.

I get this error while opening *.edge template files by the way. I'm using Remote WSL1.

**Comment by wearon** [comment] 2023-06-17 02:34
I can't believe I'm still facing this, its been months now. I even added `"emmet.extensionsPath": ["/Users/snippets.json"]` but same error and the sock in the bottom keeps switching to Output from Terminal 😡 
<img width="1154" alt="image" src="https://github.com/microsoft/vscode-emmet-helper/assets/72959518/f3918162-e657-4c73-b34e-24503b98156f">

**Comment by rzhao271** [comment] 2023-06-30 18:31
Closing because VS Code has picked up the latest emmet-helper package.
@wearon is the issue resolved for you on the latest [VS Code Insiders](https://code.visualstudio.com/insiders/)? The change has not made it to Stable yet.

**Closed as completed by rzhao271** 2023-06-30 18:31 UTC
Labels: bug, verified, author-verification-requested

**Comment by rzhao271** [comment] 2023-07-03 15:59
Verification steps:

1. Set the `emmet.extensionsPath` setting to `[2]` in the settings JSON file.
2. Open devtools.
3. Verify that a console warning shows up.

**Comment by wearon** [comment] 2023-07-03 17:46
I have not set extensionsPath to 2 yet but just updated insiders and still saw it 
<img width="1037" alt="image" src="https://github.com/microsoft/vscode-emmet-helper/assets/72959518/cbbf044b-3a37-411b-b6a3-9ce939bfdc10">

**Comment by wearon** [comment] 2023-07-04 17:44
when you say "Open devtools" in vscode, what is there referring to?
Just upgraded to latest insiders, pasting settings json + error + vscode version below
<img width="1056" alt="image" src="https://github.com/microsoft/vscode-emmet-helper/assets/72959518/89097331-b28b-48ca-87b1-3ddfb1cd48b7">

**Comment by rzhao271** [comment] 2023-07-05 16:55
"Open devtools" refers to running the "Developer: Toggle Developer Tools" command.
The logged warning, if there is one, should start with "The following emmetExtensionsPath isn't a string: "

If there isn't such a warning, I have another hypothesis. The output pane seems to come from another extension starting with the word "EDGE Language". That extension, if they're using this library, might need to pick up the latest `@vscode/emmet-helper` package.

**Comment by wearon** [comment] 2023-07-06 03:13
Thanks for sharing your hypothesis, there is this plugin with a dependency, I think this might be it. is it possible for you to install it and see if it triggers a warning?
<img width="490" alt="image" src="https://github.com/microsoft/vscode-emmet-helper/assets/72959518/c1b35ae9-0088-406b-be17-8817f24032fb">

**Comment by rzhao271** [comment] 2023-07-06 16:13
I confirmed that https://github.com/duyluonglc/vscode-edge/ is using an outdated version of vscode-emmet-helper. Please file an issue there.
